spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

server:
  port:
  ssl:
    key-store:
    key-store-password:
    key-password:

api:
  token:

mail:
  server:
  port:
  user:
  password:
  protocol:
  enable.tsl:
  admin:
telegram:
  bot:
    token:
    name:
    superusers:
    channel-chat-id:
yandex.money:
  secret:
groupmail:
  login:
  password:
vk:
  api:
    user:
      id:
      token:
    group:
      id:
      token:
  pear_id: 2000000073
